name: agentic_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.14
  - aiosignal=1.4.0
  - annotated-types=0.7.0
  - anyio=4.9.0
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - async-timeout=4.0.3
  - attrs=25.3.0
  - aws-c-auth=0.8.5
  - aws-c-cal=0.8.5
  - aws-c-common=0.11.1
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.3
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.11
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.528
  - blas=1.0
  - boost-cpp=1.78.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.9
  - certifi=2025.7.9
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - comm=0.2.2
  - datasets=3.6.0
  - debugpy=1.8.11
  - decorator=5.2.1
  - dill=0.3.8
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - filelock=3.18.0
  - frozenlist=1.7.0
  - fsspec=2025.3.0
  - gflags=2.2.2
  - glog=0.5.0
  - greenlet=3.1.1
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - httpx-sse=0.4.1
  - huggingface_hub=0.31.4
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2023.2.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jsonpatch=1.33
  - jsonpointer=2.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - langchain=0.3.26
  - langchain-core=0.3.68
  - langchain-text-splitters=0.3.8
  - langgraph-sdk=0.1.72
  - langsmith=0.3.45
  - libabseil=20250127.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.14.1
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgomp=15.1.0
  - libgrpc=1.71.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.10.0
  - libstdcxx=15.1.0
  - libthrift=0.15.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - multiprocess=0.70.15
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.5.1
  - orc=2.1.1
  - orjson=3.10.14
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytz=2025.2
  - pywin32=308
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - regex=2024.11.6
  - requests=2.32.4
  - requests-toolbelt=1.0.0
  - safetensors=0.5.3
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.13.0
  - tenacity=9.1.2
  - tk=8.6.14
  - tokenizers=0.21.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.53.2
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - backoff==2.2.1
      - bcrypt==4.3.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - chromadb==1.0.15
      - click==8.2.1
      - coloredlogs==15.0.1
      - ddg==0.2.2
      - ddgs==9.1.2
      - distro==1.9.0
      - duckduckgo-search==8.1.1
      - durationpy==0.10
      - flatbuffers==25.2.10
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - httptools==0.6.4
      - humanfriendly==10.0
      - importlib-resources==6.5.2
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kubernetes==33.1.0
      - langchain-ollama==0.3.4
      - langgraph==0.5.2
      - langgraph-checkpoint==2.1.0
      - langgraph-prebuilt==0.5.2
      - lxml==6.0.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mmh3==5.1.0
      - mpmath==1.3.0
      - oauthlib==3.3.1
      - ollama==0.5.1
      - onnxruntime==1.22.1
      - opentelemetry-api==1.35.0
      - opentelemetry-exporter-otlp-proto-common==1.35.0
      - opentelemetry-exporter-otlp-proto-grpc==1.35.0
      - opentelemetry-proto==1.35.0
      - opentelemetry-sdk==1.35.0
      - opentelemetry-semantic-conventions==0.56b0
      - ormsgpack==1.10.0
      - overrides==7.7.0
      - posthog==5.4.0
      - primp==0.15.0
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.1
      - pydef==0.0.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - referencing==0.36.2
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rpds-py==0.26.0
      - rsa==4.9.1
      - shellingham==1.5.4
      - sympy==1.14.0
      - typer==0.16.0
      - uvicorn==0.35.0
      - watchfiles==1.1.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      